name: Deploy to Nginx

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Loading SSH key setup
      uses: webfactory/ssh-agent@v0.9.0
      with: 
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with: 
        host: ${{secrets.EC2_SERVER_IP}}
        username: ${{secrets.EC2_SSH_USERNAME}}
        key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
        port: 22
        script: |
          cd /var/www/paynow/react-nodejs-paynow/PayNow/
          sudo rm -rf dist
          cd /var/www/paynow/react-nodejs-paynow/
          sudo git checkout .
          sudo git pull origin production
          cd /var/www/paynow/react-nodejs-paynow/PayNow/
          sudo npm install
          sudo npm run build
          sudo systemctl restart nginx